### ISSUE TITLE
Show all orders in history "Orders" tab

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-member-history#13]
This tab currently limits the view to exclude certain order statuses. It should be updated to include any status and we could possibly offer a filter to adjust which status are included.

https://github.com/strangerstudios/pmpro-member-history/blob/4f2919ce7feb7997e5f345561e5965ad496a6668/pmpro-member-history.php#L23

**Comment by arnalyse** [comment]
That feature is exactly what we were hoping and looking for 👍 

We would love to include the status 'pending' there, and could do exactly this if a filter would be added 🙃

**Comment by kimcoleman** [comment]
We may still consider adding a filter for what status to show, otherwise this PR resolves the issue: https://github.com/strangerstudios/pmpro-member-history/pull/12
