### ISSUE TITLE
Filtering levels on Member Value Report page redirects to Members List

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-member-history#14]
To recreate this issue do the following steps:

1. Navigate to the Member Value Report page.
2. Choose a level from the select field, any level.
3. This should redirect you to the members list page.

**Comment by andrewlimaza** [comment]
Working on a fix for this :)

**Comment by kimcoleman** [comment]
Fixed in https://github.com/strangerstudios/pmpro-member-history/commit/f5f9b28f8dc3a007b3cfea342c109aff41b59452
