### ISSUE TITLE
BUG: Member Value Report widget displays deleted members; throws PHP Notice

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-member-history#17]
The Member Value Reports widget on the Reports dashboard displays deleted users and throws PHP Notices for those users which don't exist.

**Support Ticket (Mods only)**
https://www.paidmembershipspro.com/forums/topic/bug-trying-to-get-property-display_name-error-after-upgrade-to-v2-1-0/

**Comment by kimcoleman** [comment]
Fixed in https://github.com/strangerstudios/pmpro-member-history/commit/b4a19e6e95646c6702b2a40c28ee67f07fde6c47

**Comment by tictag** [comment]
@messica Will there be a release to this Add On or should I apply this fix manually? (I'm the customer that originally reported this issue via the Support Ticket).

**Comment by kimcoleman** [comment]
We have included the fix in the latest version of the plugin and will be pushing a release soon.
