### ISSUE TITLE
Member history not working for PayPal Express

### ISSUE THREAD

**Issue by hbcondo** [strangerstudios/pmpro-member-history#20]
My site implements both Stripe and PayPal Express via the [plugin](https://www.paidmembershipspro.com/add-ons/pmpro-add-paypal-express-option-checkout/) but the full member history only appears for members that pay with Stripe. For members that pay with PayPal, only one entry appears in the WordPress Admin users page but the entire payment history appears correctly in PayPal. 

See attached screenshots; why doesn't PayPal transactions show up in WordPress with this add-on?

![image](https://user-images.githubusercontent.com/306958/67255158-94e52500-f435-11e9-9c7b-535f12909d90.png)

![image](https://user-images.githubusercontent.com/306958/67255187-b2b28a00-f435-11e9-9494-4dd475fba14a.png)

**Comment by kimcoleman** [comment]
Your PayPal IPN is not properly configured. Recurring orders should be created in your PMPro site database for every payment made.

Please refer to this guide or open a ticket in our support area for ongoing help.

https://www.paidmembershipspro.com/troubleshooting-paypal-ipn-issues-with-paypal-express-paypal-standard-or-paypal-website-payments-pro/

**Comment by hbcondo** [comment]
@kimcoleman, we reviewed your link but are still experiencing this issue. Others have logged issues similar to this, particularly this:

BUG: PMPro Core – IPNs for Recurring Payment Payments Are Not Logged

https://github.com/strangerstudios/paid-memberships-pro/issues/1187
